### ISSUE TITLE
新的图片丢进去之后缩略图不能显示 如果当作封面 点都点不近

### ISSUE THREAD

**Issue by 502647092** [litten/zing-gallery#1]
![图片](https://dn-coding-net-production-pp.qbox.me/8787abc0-24cd-49e9-88a0-f96779f267a4.png)

**Comment by litten** [comment]
不太好定位，因为我这边是好的…
怀疑是图片”生成缩略图“或”提取图片信息“时报错，能否提供下控制台报错的信息？
或者把其中一张图片发给我：litten225@qq.com

**Comment by 502647092** [comment]
已经发送给你了 
我加了调试代码 应该是生成缩略图的时候的问题
点进去还是可以看到的
后台没有报错

**Comment by litten** [comment]
![2016-10-25 12 20 29](https://cloud.githubusercontent.com/assets/2024949/19653903/ddf90efe-9a48-11e6-8035-ca3e708ddc10.png)

添加了一个侦听photos变化重新生成缩略图的逻辑，我这边已正常。
但你需要重新执行一下`npm install`安装依赖。

如果实在不行，试试：
1、删除根目录生成的`tmp`文件夹
2、停掉进程，重新跑`npm run start`

**Comment by 502647092** [comment]
![image](https://cloud.githubusercontent.com/assets/10203793/19876180/690b0572-a00e-11e6-8d37-ae478c3950a1.png)
好像还是不行哦
我感觉是生成缩略图的问题 不是重新生成的问题
![image](https://cloud.githubusercontent.com/assets/10203793/19876193/87ffe27c-a00e-11e6-89c0-6814df4d7b1b.png)
而且后台也没有报错

**Comment by litten** [comment]
请提供一下系统信息，以及node、npm版本。我再看看

**Comment by 502647092** [comment]
![image](https://cloud.githubusercontent.com/assets/10203793/20178873/23b240d0-a78e-11e6-8e60-cdf873ddf6d3.png)

**Comment by suifengqjn** [comment]
想问一下，没有index.html怎么放到github.io的博客里面

**Comment by snksos** [comment]
@502647092 解决了吗？

**Comment by 502647092** [comment]
@suifengqjn 这个是nodejs的项目 不是静态网页的

**Comment by 502647092** [comment]
@snksos 没有 还是空白的 后来就没用了

**Comment by snksos** [comment]
@502647092 我没有研究代码，只是进行了白盒测试，发现相册内单张图片的命名必须是 IMG_XXX 的格式才行！

**Comment by 502647092** [comment]
@snksos 不清楚 作者貌似好久没出现了

**Comment by litten** [comment]
额不好意思，我忘了这个bug…抱歉
@snksos 居然是命名的问题吗？我晚上有空确认下

**Comment by snksos** [comment]
@litten 不好意思，我重试了别的命名（aa.jpg），是可以的，但是仅仅可以放进相册一张照片，超过一张之后，点击相册的时候，一直处在加载中的状态（点击不进去），过一会之后响应超时。
一言以蔽之：相册内超过一张照片即响应超时
麻烦作者有时间检查一下这个问题吧

补充：
node 版本 v6.6.0
npm 版本 3.10.3
点击异常相册之后，控制台显示：
(node:1810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'Time' of nul

**Comment by 502647092** [comment]
@litten 应该还是略缩图生成的问题吧

**Comment by litten** [comment]
好的，信息很全，多谢提供

**Comment by snksos** [comment]
是读取图片的代码问题，读取照片信息时应该没做异常处理。因为作者只是处理了相机相片，相机相片能读取到光圈、相机型号等相关信息，而手机或者别的图片因无法读取到而造成异常崩溃。

作者有时间看一下修复下这个BUG吧，我的Nodejs不灵光，无法贡献代码了

**Comment by litten** [comment]
@502647092 @suifengqjn @snksos 
更新了，是取不到图片生成的时间，排序函数报错导致。
请更新再试试。

**Comment by snksos** [comment]
thanks!

**Comment by 502647092** [comment]
@litten 好 我试下

**Comment by 502647092** [comment]
已经可以了
